[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zorox = "5pj7QiUhJyqeYQv64pCNzVs2X8LfU2fGpBAKAE3c718p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
